(function() {var implementors = {
"relay_auth":[["impl Fail for <a class=\"struct\" href=\"relay_auth/struct.ParseRelayVersionError.html\" title=\"struct relay_auth::ParseRelayVersionError\">ParseRelayVersionError</a>"],["impl Fail for <a class=\"enum\" href=\"relay_auth/enum.KeyParseError.html\" title=\"enum relay_auth::KeyParseError\">KeyParseError</a>"],["impl Fail for <a class=\"enum\" href=\"relay_auth/enum.UnpackError.html\" title=\"enum relay_auth::UnpackError\">UnpackError</a>"]],
"relay_config":[["impl Fail for <a class=\"struct\" href=\"relay_config/struct.ConfigError.html\" title=\"struct relay_config::ConfigError\">ConfigError</a>"],["impl Fail for <a class=\"enum\" href=\"relay_config/enum.ConfigErrorKind.html\" title=\"enum relay_config::ConfigErrorKind\">ConfigErrorKind</a>"],["impl Fail for <a class=\"enum\" href=\"relay_config/enum.UpstreamError.html\" title=\"enum relay_config::UpstreamError\">UpstreamError</a>"],["impl Fail for <a class=\"enum\" href=\"relay_config/enum.UpstreamParseError.html\" title=\"enum relay_config::UpstreamParseError\">UpstreamParseError</a>"]],
"relay_general":[["impl Fail for <a class=\"enum\" href=\"relay_general/pii/enum.PiiConfigError.html\" title=\"enum relay_general::pii::PiiConfigError\">PiiConfigError</a>"],["impl Fail for <a class=\"enum\" href=\"relay_general/pii/enum.ScrubMinidumpError.html\" title=\"enum relay_general::pii::ScrubMinidumpError\">ScrubMinidumpError</a>"],["impl Fail for <a class=\"struct\" href=\"relay_general/processor/struct.UnknownValueTypeError.html\" title=\"struct relay_general::processor::UnknownValueTypeError\">UnknownValueTypeError</a>"],["impl Fail for <a class=\"enum\" href=\"relay_general/processor/enum.InvalidSelectorError.html\" title=\"enum relay_general::processor::InvalidSelectorError\">InvalidSelectorError</a>"],["impl Fail for <a class=\"struct\" href=\"relay_general/protocol/struct.ParseSessionStatusError.html\" title=\"struct relay_general::protocol::ParseSessionStatusError\">ParseSessionStatusError</a>"],["impl Fail for <a class=\"struct\" href=\"relay_general/protocol/struct.InvalidRegVal.html\" title=\"struct relay_general::protocol::InvalidRegVal\">InvalidRegVal</a>"],["impl Fail for <a class=\"struct\" href=\"relay_general/protocol/struct.ParseLevelError.html\" title=\"struct relay_general::protocol::ParseLevelError\">ParseLevelError</a>"],["impl Fail for <a class=\"enum\" href=\"relay_general/types/enum.ProcessingAction.html\" title=\"enum relay_general::types::ProcessingAction\">ProcessingAction</a>"]],
"relay_metrics":[["impl Fail for <a class=\"struct\" href=\"relay_metrics/struct.ParseBucketError.html\" title=\"struct relay_metrics::ParseBucketError\">ParseBucketError</a>"],["impl Fail for <a class=\"struct\" href=\"relay_metrics/struct.AggregateMetricsError.html\" title=\"struct relay_metrics::AggregateMetricsError\">AggregateMetricsError</a>"]],
"relay_profiling":[["impl Fail for <a class=\"enum\" href=\"relay_profiling/enum.ProfileError.html\" title=\"enum relay_profiling::ProfileError\">ProfileError</a>"]],
"relay_quotas":[["impl Fail for <a class=\"enum\" href=\"relay_quotas/enum.RateLimitingError.html\" title=\"enum relay_quotas::RateLimitingError\">RateLimitingError</a>"]],
"relay_redis":[["impl Fail for <a class=\"enum\" href=\"relay_redis/enum.RedisError.html\" title=\"enum relay_redis::RedisError\">RedisError</a>"]],
"relay_server":[["impl Fail for <a class=\"struct\" href=\"relay_server/struct.ServerError.html\" title=\"struct relay_server::ServerError\">ServerError</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()