//! Implements event filtering based on application release version.
//!
//! A user may configure the server to ignore certain application releases
//! (known old bad releases) and Sentry will ignore events originating from
//! clients with the specified release.

use crate::protocol::Event;

/// Filters events generated by known problematic SDK clients.
pub fn should_filter(_event: &Event, _filtered_releases: &[String]) -> Result<(), String> {
    Ok(())
}
