var N = null;var sourcesIndex = {};
sourcesIndex["document_metrics"] = {"name":"","files":["main.rs"]};
sourcesIndex["generate_schema"] = {"name":"","files":["main.rs"]};
sourcesIndex["process_event"] = {"name":"","files":["main.rs"]};
sourcesIndex["relay"] = {"name":"","files":["alloc.rs","cli.rs","cliapp.rs","main.rs","setup.rs","utils.rs"]};
sourcesIndex["relay_auth"] = {"name":"","files":["lib.rs"]};
sourcesIndex["relay_cabi"] = {"name":"","files":["auth.rs","constants.rs","core.rs","ffi.rs","lib.rs","processing.rs"]};
sourcesIndex["relay_common"] = {"name":"","files":["cell.rs","constants.rs","glob.rs","lib.rs","macros.rs","project.rs","retry.rs","time.rs","utils.rs"]};
sourcesIndex["relay_common_actors"] = {"name":"","files":["controller.rs","lib.rs"]};
sourcesIndex["relay_config"] = {"name":"","files":["byte_size.rs","config.rs","lib.rs","upstream.rs"]};
sourcesIndex["relay_crash"] = {"name":"","files":["lib.rs"]};
sourcesIndex["relay_ffi"] = {"name":"","files":["lib.rs"]};
sourcesIndex["relay_ffi_macros"] = {"name":"","files":["lib.rs"]};
sourcesIndex["relay_filter"] = {"name":"","files":["browser_extensions.rs","client_ips.rs","common.rs","config.rs","csp.rs","error_messages.rs","legacy_browsers.rs","lib.rs","localhost.rs","releases.rs","web_crawlers.rs"]};
sourcesIndex["relay_general"] = {"name":"","dirs":[{"name":"pii","files":["attachments.rs","builtin.rs","compiledconfig.rs","config.rs","convert.rs","generate_selectors.rs","legacy.rs","minidumps.rs","mod.rs","processor.rs","redactions.rs","regexes.rs","utils.rs"]},{"name":"processor","files":["attrs.rs","chunks.rs","funcs.rs","impls.rs","mod.rs","selector.rs","size.rs","traits.rs"]},{"name":"protocol","files":["breadcrumb.rs","breakdowns.rs","client_report.rs","clientsdk.rs","constants.rs","contexts.rs","debugmeta.rs","event.rs","exception.rs","fingerprint.rs","logentry.rs","measurements.rs","mechanism.rs","metrics.rs","mod.rs","relay_info.rs","request.rs","schema.rs","security_report.rs","session.rs","span.rs","stacktrace.rs","tags.rs","templateinfo.rs","thread.rs","types.rs","user.rs","user_report.rs"]},{"name":"store","dirs":[{"name":"normalize","files":["breakdowns.rs","contexts.rs","logentry.rs","mechanism.rs","request.rs","spans.rs","stacktrace.rs","user_agent.rs"]}],"files":["clock_drift.rs","event_error.rs","geo.rs","legacy.rs","mod.rs","normalize.rs","remove_other.rs","schema.rs","transactions.rs","trimming.rs"]},{"name":"types","files":["annotated.rs","impls.rs","meta.rs","mod.rs","span_attributes.rs","traits.rs","value.rs"]}],"files":["lib.rs","macros.rs","user_agent.rs"]};
sourcesIndex["relay_general_derive"] = {"name":"","files":["empty.rs","jsonschema.rs","lib.rs","process.rs"]};
sourcesIndex["relay_log"] = {"name":"","files":["lib.rs","sentry_failure.rs","setup.rs","test.rs","utils.rs"]};
sourcesIndex["relay_metrics"] = {"name":"","files":["aggregation.rs","lib.rs","protocol.rs","statsd.rs"]};
sourcesIndex["relay_quotas"] = {"name":"","files":["lib.rs","quota.rs","rate_limit.rs","redis.rs"]};
sourcesIndex["relay_redis"] = {"name":"","files":["config.rs","lib.rs","real.rs"]};
sourcesIndex["relay_sampling"] = {"name":"","files":["lib.rs"]};
sourcesIndex["relay_server"] = {"name":"","dirs":[{"name":"actors","files":["envelopes.rs","healthcheck.rs","mod.rs","outcome.rs","outcome_aggregator.rs","project.rs","project_cache.rs","project_local.rs","project_redis.rs","project_upstream.rs","relays.rs","server.rs","store.rs","upstream.rs"]},{"name":"body","files":["mod.rs","peek_line.rs","request_body.rs","store_body.rs"]},{"name":"endpoints","files":["attachments.rs","common.rs","envelope.rs","events.rs","forward.rs","healthcheck.rs","minidump.rs","mod.rs","outcomes.rs","project_configs.rs","public_keys.rs","security_report.rs","statics.rs","store.rs","unreal.rs"]},{"name":"extractors","files":["decoder.rs","forwarded_for.rs","mod.rs","request_meta.rs","shared_payload.rs","signed_json.rs","start_time.rs"]},{"name":"metrics_extraction","files":["conditional_tagging.rs","mod.rs","sessions.rs","transactions.rs","utils.rs"]},{"name":"utils","files":["actix.rs","api.rs","dynamic_sampling.rs","error_boundary.rs","kafka.rs","mod.rs","multipart.rs","native.rs","param_parser.rs","profile.rs","rate_limits.rs","request.rs","shutdown.rs","sizes.rs","timer.rs","tracked_future.rs","unreal.rs","with_outcome.rs"]}],"files":["constants.rs","envelope.rs","http.rs","lib.rs","middlewares.rs","service.rs","statsd.rs"]};
sourcesIndex["relay_statsd"] = {"name":"","files":["lib.rs"]};
sourcesIndex["relay_test"] = {"name":"","files":["lib.rs"]};
sourcesIndex["scrub_minidump"] = {"name":"","files":["main.rs"]};
createSourceSidebar();
