// country_geoscheme.rs
use std::collections::HashMap;
use std::fmt;

/** Geoscheme regions as defined by UN M49 standerds, to value corresponds to the region code */
pub enum Geoscheme {
    NorthernAmerica = 021,
    CentralAmerica = 013,
    Caribbean = 029,
    SouthAmerica = 005,
    NorthernEurope = 154,
    WesternEurope = 155,
    SouthernEurope = 039,
    EasternEurope = 151,
    EasternAsia = 030,
    SouthernAsia = 034,
    SouthEasternAsia = 035,
    WesternAsia = 145,
    CentralAsia = 143,
    NorthernAfrica = 7,
    WesternAfrica = 011,
    MiddleAfrica = 017,
    EasternAfrica = 014,
    SouthernAfrica = 018,
    Melanesia = 054,
    Micronesia = 057,
    Polynesia = 061,
    AustraliaAndNewZealand = 053,
}

impl fmt::Display for Geoscheme {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let geoscheme_str = match self {
            Geoscheme::NorthernAmerica => "Northern America",
            Geoscheme::SouthAmerica => "Southern America",
            Geoscheme::CentralAmerica => "Central America",
            Geoscheme::Caribbean => "Caribbean",
            Geoscheme::NorthernAfrica => "Northern Africa",
            Geoscheme::SouthernEurope => "Southern Europe",
            Geoscheme::WesternAsia => "Western Asia",
            Geoscheme::EasternEurope => "Eastern Europe",
            Geoscheme::EasternAsia => "Eastern Asia",
            Geoscheme::SouthEasternAsia => "South-Eastern Asia",
            Geoscheme::CentralAsia => "Central Asia",
            Geoscheme::SouthernAsia => "Southern Asia",
            Geoscheme::WesternEurope => "Western Europe",
            Geoscheme::NorthernEurope => "Northern Europe",
            Geoscheme::MiddleAfrica => "Middle Africa",
            Geoscheme::WesternAfrica => "Western Africa",
            Geoscheme::EasternAfrica => "Eastern Africa",
            Geoscheme::SouthernAfrica => "Southern Africa",
            Geoscheme::Melanesia => "Melanesia",
            Geoscheme::Micronesia => "Micronesia",
            Geoscheme::Polynesia => "Polynesia",
            Geoscheme::AustraliaAndNewZealand => "Australia and New Zealand",
        };
        write!(f, "{}", geoscheme_str)
    }
}

/**
 * Maps ISO 2 letter country codes to geoscheme regions based on the UN M.49 standard.
 */
pub fn get_country_to_geoscheme() -> HashMap<&'static str, Geoscheme> {
    HashMap::from([
        ("AF", Geoscheme::SouthernAsia),
        ("AL", Geoscheme::SouthernEurope),
        ("DZ", Geoscheme::NorthernAfrica),
        ("AS", Geoscheme::Polynesia),
        ("AD", Geoscheme::SouthernEurope),
        ("AO", Geoscheme::MiddleAfrica),
        ("AG", Geoscheme::Caribbean),
        ("AR", Geoscheme::SouthAmerica),
        ("AM", Geoscheme::WesternAsia),
        ("AU", Geoscheme::AustraliaAndNewZealand),
        ("AT", Geoscheme::WesternEurope),
        ("AZ", Geoscheme::WesternAsia),
        ("BS", Geoscheme::Caribbean),
        ("BH", Geoscheme::WesternAsia),
        ("BD", Geoscheme::SouthernAsia),
        ("BB", Geoscheme::Caribbean),
        ("BY", Geoscheme::EasternEurope),
        ("BE", Geoscheme::WesternEurope),
        ("BZ", Geoscheme::CentralAmerica),
        ("BJ", Geoscheme::WesternAfrica),
        ("BM", Geoscheme::NorthernAmerica),
        ("BT", Geoscheme::SouthernAsia),
        ("BO", Geoscheme::SouthAmerica),
        ("BA", Geoscheme::SouthernEurope),
        ("BW", Geoscheme::SouthernAfrica),
        ("BR", Geoscheme::SouthAmerica),
        ("BN", Geoscheme::SouthEasternAsia),
        ("BG", Geoscheme::EasternEurope),
        ("BF", Geoscheme::WesternAfrica),
        ("BI", Geoscheme::EasternAfrica),
        ("CV", Geoscheme::WesternAfrica),
        ("KH", Geoscheme::SouthEasternAsia),
        ("CM", Geoscheme::MiddleAfrica),
        ("CA", Geoscheme::NorthernAmerica),
        ("KY", Geoscheme::Caribbean),
        ("CF", Geoscheme::MiddleAfrica),
        ("TD", Geoscheme::MiddleAfrica),
        ("CL", Geoscheme::SouthAmerica),
        ("CN", Geoscheme::EasternAsia),
        ("CO", Geoscheme::SouthAmerica),
        ("KM", Geoscheme::EasternAfrica),
        ("CG", Geoscheme::MiddleAfrica),
        ("CR", Geoscheme::CentralAmerica),
        ("CI", Geoscheme::WesternAfrica),
        ("HR", Geoscheme::SouthernEurope),
        ("CU", Geoscheme::Caribbean),
        ("CY", Geoscheme::WesternAsia),
        ("CZ", Geoscheme::EasternEurope),
        ("DK", Geoscheme::NorthernEurope),
        ("DJ", Geoscheme::EasternAfrica),
        ("DM", Geoscheme::Caribbean),
        ("DO", Geoscheme::Caribbean),
        ("EC", Geoscheme::SouthAmerica),
        ("EG", Geoscheme::NorthernAfrica),
        ("SV", Geoscheme::CentralAmerica),
        ("GQ", Geoscheme::MiddleAfrica),
        ("ER", Geoscheme::EasternAfrica),
        ("EE", Geoscheme::NorthernEurope),
        ("ET", Geoscheme::EasternAfrica),
        ("FJ", Geoscheme::Melanesia),
        ("FI", Geoscheme::NorthernEurope),
        ("FR", Geoscheme::WesternEurope),
        ("GA", Geoscheme::MiddleAfrica),
        ("GM", Geoscheme::WesternAfrica),
        ("GE", Geoscheme::WesternAsia),
        ("DE", Geoscheme::WesternEurope),
        ("GH", Geoscheme::WesternAfrica),
        ("GR", Geoscheme::SouthernEurope),
        ("GD", Geoscheme::Caribbean),
        ("GT", Geoscheme::CentralAmerica),
        ("GN", Geoscheme::WesternAfrica),
        ("GW", Geoscheme::WesternAfrica),
        ("GY", Geoscheme::SouthAmerica),
        ("HT", Geoscheme::Caribbean),
        ("HN", Geoscheme::CentralAmerica),
        ("HU", Geoscheme::EasternEurope),
        ("IS", Geoscheme::NorthernEurope),
        ("IN", Geoscheme::SouthernAsia),
        ("ID", Geoscheme::SouthEasternAsia),
        ("IR", Geoscheme::SouthernAsia),
        ("IQ", Geoscheme::WesternAsia),
        ("IE", Geoscheme::NorthernEurope),
        ("IL", Geoscheme::WesternAsia),
        ("IT", Geoscheme::SouthernEurope),
        ("JM", Geoscheme::Caribbean),
        ("JP", Geoscheme::EasternAsia),
        ("JO", Geoscheme::WesternAsia),
        ("KZ", Geoscheme::CentralAsia),
        ("KE", Geoscheme::EasternAfrica),
        ("KI", Geoscheme::Micronesia),
        ("KP", Geoscheme::EasternAsia),
        ("KR", Geoscheme::EasternAsia),
        ("KW", Geoscheme::WesternAsia),
        ("KG", Geoscheme::CentralAsia),
        ("LA", Geoscheme::SouthEasternAsia),
        ("LV", Geoscheme::NorthernEurope),
        ("LB", Geoscheme::WesternAsia),
        ("LS", Geoscheme::SouthernAfrica),
        ("LR", Geoscheme::WesternAfrica),
        ("LY", Geoscheme::NorthernAfrica),
        ("LI", Geoscheme::WesternEurope),
        ("LT", Geoscheme::NorthernEurope),
        ("LU", Geoscheme::WesternEurope),
        ("MG", Geoscheme::EasternAfrica),
        ("MW", Geoscheme::EasternAfrica),
        ("MY", Geoscheme::SouthEasternAsia),
        ("MV", Geoscheme::SouthernAsia),
        ("ML", Geoscheme::WesternAfrica),
        ("MT", Geoscheme::SouthernEurope),
        ("MH", Geoscheme::Micronesia),
        ("MR", Geoscheme::WesternAfrica),
        ("MU", Geoscheme::EasternAfrica),
        ("MX", Geoscheme::CentralAmerica),
        ("FM", Geoscheme::Micronesia),
        ("MD", Geoscheme::EasternEurope),
        ("MC", Geoscheme::WesternEurope),
        ("MN", Geoscheme::EasternAsia),
        ("ME", Geoscheme::SouthernEurope),
        ("MA", Geoscheme::NorthernAfrica),
        ("MZ", Geoscheme::EasternAfrica),
        ("MM", Geoscheme::SouthEasternAsia),
        ("NA", Geoscheme::SouthernAfrica),
        ("NR", Geoscheme::Micronesia),
        ("NP", Geoscheme::SouthernAsia),
        ("NL", Geoscheme::WesternEurope),
        ("NZ", Geoscheme::AustraliaAndNewZealand),
        ("NI", Geoscheme::CentralAmerica),
        ("NE", Geoscheme::WesternAfrica),
        ("NG", Geoscheme::WesternAfrica),
        ("NO", Geoscheme::NorthernEurope),
        ("OM", Geoscheme::WesternAsia),
        ("PK", Geoscheme::SouthernAsia),
        ("PW", Geoscheme::Micronesia),
        ("PA", Geoscheme::CentralAmerica),
        ("PG", Geoscheme::Melanesia),
        ("PY", Geoscheme::SouthAmerica),
        ("PE", Geoscheme::SouthAmerica),
        ("PH", Geoscheme::SouthEasternAsia),
        ("PL", Geoscheme::EasternEurope),
        ("PT", Geoscheme::SouthernEurope),
        ("QA", Geoscheme::WesternAsia),
        ("RO", Geoscheme::EasternEurope),
        ("RU", Geoscheme::EasternEurope),
        ("RW", Geoscheme::EasternAfrica),
        ("KN", Geoscheme::Caribbean),
        ("LC", Geoscheme::Caribbean),
        ("VC", Geoscheme::Caribbean),
        ("WS", Geoscheme::Polynesia),
        ("SM", Geoscheme::SouthernEurope),
        ("ST", Geoscheme::MiddleAfrica),
        ("SA", Geoscheme::WesternAsia),
        ("SN", Geoscheme::WesternAfrica),
        ("RS", Geoscheme::SouthernEurope),
        ("SC", Geoscheme::EasternAfrica),
        ("SL", Geoscheme::WesternAfrica),
        ("SG", Geoscheme::SouthEasternAsia),
        ("SK", Geoscheme::EasternEurope),
        ("SI", Geoscheme::SouthernEurope),
        ("SB", Geoscheme::Melanesia),
        ("SO", Geoscheme::EasternAfrica),
        ("ZA", Geoscheme::SouthernAfrica),
        ("SS", Geoscheme::EasternAfrica),
        ("ES", Geoscheme::SouthernEurope),
        ("LK", Geoscheme::SouthernAsia),
        ("SD", Geoscheme::NorthernAfrica),
        ("SR", Geoscheme::SouthAmerica),
        ("SZ", Geoscheme::SouthernAfrica),
        ("SE", Geoscheme::NorthernEurope),
        ("CH", Geoscheme::WesternEurope),
        ("SY", Geoscheme::WesternAsia),
        ("TJ", Geoscheme::CentralAsia),
        ("TZ", Geoscheme::EasternAfrica),
        ("TH", Geoscheme::SouthEasternAsia),
        ("TL", Geoscheme::SouthEasternAsia),
        ("TG", Geoscheme::WesternAfrica),
        ("TO", Geoscheme::Polynesia),
        ("TT", Geoscheme::Caribbean),
        ("TN", Geoscheme::NorthernAfrica),
        ("TR", Geoscheme::WesternAsia),
        ("TM", Geoscheme::CentralAsia),
        ("TV", Geoscheme::Polynesia),
        ("UG", Geoscheme::EasternAfrica),
        ("UA", Geoscheme::EasternEurope),
        ("AE", Geoscheme::WesternAsia),
        ("GB", Geoscheme::NorthernEurope),
        ("US", Geoscheme::NorthernAmerica),
        ("UY", Geoscheme::SouthAmerica),
        ("UZ", Geoscheme::CentralAsia),
        ("VU", Geoscheme::Melanesia),
        ("VE", Geoscheme::SouthAmerica),
        ("VN", Geoscheme::SouthEasternAsia),
        ("YE", Geoscheme::WesternAsia),
        ("ZM", Geoscheme::EasternAfrica),
        ("ZW", Geoscheme::EasternAfrica),
    ])
}
