mod convert;

use std::fmt;
use std::ops::Deref;
use std::str::FromStr;

use relay_conventions::attributes::{
    BROWSER__NAME, SENTRY__ENVIRONMENT, SENTRY__RELEASE, SENTRY__SEGMENT__NAME,
};
use relay_protocol::{
    Annotated, Array, Empty, Error, FromValue, Getter, IntoValue, Object, Val, Value,
};

use crate::processor::{Pii, ProcessValue, ProcessingState};
use crate::protocol::{
    EventId, JsonLenientString, Measurements, OperationType, OriginType, SpanId, SpanStatus,
    Timestamp, TraceId,
};

#[derive(Clone, Debug, Default, PartialEq, Empty, FromValue, IntoValue, ProcessValue)]
#[metastructure(process_func = "process_span", value_type = "Span", trim = false)]
pub struct Span {
    /// Timestamp when the span was ended.
    #[metastructure(required = true)]
    pub timestamp: Annotated<Timestamp>,

    /// Timestamp when the span started.
    #[metastructure(required = true)]
    pub start_timestamp: Annotated<Timestamp>,

    /// The amount of time in milliseconds spent in this span,
    /// excluding its immediate child spans.
    pub exclusive_time: Annotated<f64>,

    /// Span type (see `OperationType` docs).
    #[metastructure(max_chars = 128)]
    pub op: Annotated<OperationType>,

    /// The Span id.
    #[metastructure(required = true)]
    pub span_id: Annotated<SpanId>,

    /// The ID of the span enclosing this span.
    pub parent_span_id: Annotated<SpanId>,

    /// The ID of the trace the span belongs to.
    #[metastructure(required = true)]
    pub trace_id: Annotated<TraceId>,

    /// A unique identifier for a segment within a trace (8 byte hexadecimal string).
    ///
    /// For spans embedded in transactions, the `segment_id` is the `span_id` of the containing
    /// transaction.
    pub segment_id: Annotated<SpanId>,

    /// Whether or not the current span is the root of the segment.
    pub is_segment: Annotated<bool>,

    /// Indicates whether a span's parent is remote.
    ///
    /// For OpenTelemetry spans, this is derived from span flags bits 8 and 9. See
    /// `SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK` and `SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK`.
    ///
    /// The states are:
    ///  - `empty`: unknown
    ///  - `false`: is not remote
    ///  - `true`: is remote
    pub is_remote: Annotated<bool>,

    /// The status of a span.
    pub status: Annotated<SpanStatus>,

    /// Human readable description of a span (e.g. method URL).
    #[metastructure(pii = "maybe")]
    pub description: Annotated<String>,

    /// Arbitrary tags on a span, like on the top-level event.
    #[metastructure(pii = "maybe")]
    pub tags: Annotated<Object<JsonLenientString>>,

    /// The origin of the span indicates what created the span (see [OriginType] docs).
    #[metastructure(max_chars = 128, allow_chars = "a-zA-Z0-9_.")]
    pub origin: Annotated<OriginType>,

    /// ID of a profile that can be associated with the span.
    pub profile_id: Annotated<EventId>,

    /// Arbitrary additional data on a span.
    ///
    /// Besides arbitrary user data, this object also contains SDK-provided fields used by the
    /// product (see <https://develop.sentry.dev/sdk/performance/span-data-conventions/>).
    #[metastructure(pii = "true")]
    pub data: Annotated<SpanData>,

    /// Links from this span to other spans
    #[metastructure(pii = "maybe")]
    pub links: Annotated<Array<SpanLink>>,

    /// Tags generated by Relay. These tags are a superset of the tags set on span metrics.
    pub sentry_tags: Annotated<SentryTags>,

    /// Timestamp when the span has been received by Sentry.
    pub received: Annotated<Timestamp>,

    /// Measurements which holds observed values such as web vitals.
    #[metastructure(skip_serialization = "empty")]
    #[metastructure(omit_from_schema)] // we only document error events for now
    pub measurements: Annotated<Measurements>,

    /// Platform identifier.
    ///
    /// See [`Event::platform`](`crate::protocol::Event::platform`).
    #[metastructure(skip_serialization = "empty")]
    pub platform: Annotated<String>,

    /// Whether the span is a segment span that was converted from a transaction.
    #[metastructure(skip_serialization = "empty")]
    pub was_transaction: Annotated<bool>,

    // Used to clarify the relationship between parents and children, or to distinguish between
    // spans, e.g. a `server` and `client` span with the same name.
    //
    // See <https://opentelemetry.io/docs/specs/otel/trace/api/#spankind>
    #[metastructure(skip_serialization = "empty", trim = false)]
    pub kind: Annotated<SpanKind>,

    /// Additional arbitrary fields for forwards compatibility.
    #[metastructure(additional_properties, pii = "maybe")]
    pub other: Object<Value>,
}

impl Span {
    /// Returns the value of an attribute on the span.
    ///
    /// This primarily looks up the attribute in the `data` object, but falls back to the `tags`
    /// object if the attribute is not found.
    fn attribute(&self, key: &str) -> Option<Val<'_>> {
        Some(match Getter::get_value(self.data.value()?, key) {
            Some(value) => value,
            None => self.tags.value()?.get(key)?.as_str()?.into(),
        })
    }
}

impl Getter for Span {
    fn get_value(&self, path: &str) -> Option<Val<'_>> {
        let span_prefix = path.strip_prefix("span.");
        if let Some(span_prefix) = span_prefix {
            return Some(match span_prefix {
                "exclusive_time" => self.exclusive_time.value()?.into(),
                "description" => self.description.as_str()?.into(),
                "op" => self.op.as_str()?.into(),
                "span_id" => self.span_id.value()?.into(),
                "parent_span_id" => self.parent_span_id.value()?.into(),
                "trace_id" => self.trace_id.value()?.deref().into(),
                "status" => self.status.as_str()?.into(),
                "is_segment" => self.is_segment.value()?.into(),
                "origin" => self.origin.as_str()?.into(),
                "duration" => {
                    let start_timestamp = *self.start_timestamp.value()?;
                    let timestamp = *self.timestamp.value()?;
                    relay_common::time::chrono_to_positive_millis(timestamp - start_timestamp)
                        .into()
                }
                "was_transaction" => self.was_transaction.value().unwrap_or(&false).into(),
                path => {
                    if let Some(key) = path.strip_prefix("tags.") {
                        self.tags.value()?.get(key)?.as_str()?.into()
                    } else if let Some(key) = path.strip_prefix("data.") {
                        self.attribute(key)?
                    } else if let Some(key) = path.strip_prefix("sentry_tags.") {
                        self.sentry_tags.value()?.get_value(key)?
                    } else {
                        let rest = path.strip_prefix("measurements.")?;
                        let name = rest.strip_suffix(".value")?;
                        self.measurements
                            .value()?
                            .get(name)?
                            .value()?
                            .value
                            .value()?
                            .into()
                    }
                }
            });
        }

        // For backward compatibility with event-based rules, we try to support `event.` fields also
        // for a span.
        let event_prefix = path.strip_prefix("event.")?;
        Some(match event_prefix {
            "release" => self.data.value()?.get_str(SENTRY__RELEASE)?.into(),
            "environment" => self.data.value()?.get_str(SENTRY__ENVIRONMENT)?.into(),
            "transaction" => self.data.value()?.get_str(SENTRY__SEGMENT__NAME)?.into(),
            "contexts.browser.name" => self.data.value()?.get_str(BROWSER__NAME)?.into(),
            // TODO: we might want to add additional fields once they are added to the span.
            _ => return None,
        })
    }
}

/// Indexable fields added by sentry (server-side).
#[derive(Clone, Debug, Default, PartialEq, Empty, FromValue, IntoValue, ProcessValue)]
#[metastructure(trim = false, pii = "maybe")]
pub struct SentryTags {
    pub release: Annotated<String>,
    #[metastructure(pii = "true")]
    pub user: Annotated<String>,
    #[metastructure(pii = "true", field = "user.id")]
    pub user_id: Annotated<String>,
    #[metastructure(pii = "true", field = "user.ip")]
    pub user_ip: Annotated<String>,
    #[metastructure(pii = "true", field = "user.username")]
    pub user_username: Annotated<String>,
    #[metastructure(pii = "true", field = "user.email")]
    pub user_email: Annotated<String>,
    pub environment: Annotated<String>,
    #[metastructure(field = "transaction.method")]
    pub transaction_method: Annotated<String>,
    #[metastructure(field = "transaction.op")]
    pub transaction_op: Annotated<String>,
    #[metastructure(field = "browser.name")]
    pub browser_name: Annotated<String>,
    #[metastructure(field = "sdk.name")]
    pub sdk_name: Annotated<String>,
    #[metastructure(field = "sdk.version")]
    pub sdk_version: Annotated<String>,
    pub platform: Annotated<String>,
    // `"true"` if the transaction was sent by a mobile SDK(String).
    pub mobile: Annotated<String>,
    #[metastructure(field = "device.class")]
    pub device_class: Annotated<String>,
    #[metastructure(field = "device.family")]
    pub device_family: Annotated<String>,
    #[metastructure(field = "device.arch")]
    pub device_arch: Annotated<String>,
    #[metastructure(field = "device.battery_level")]
    pub device_battery_level: Annotated<String>,
    #[metastructure(field = "device.brand")]
    pub device_brand: Annotated<String>,
    #[metastructure(field = "device.charging")]
    pub device_charging: Annotated<String>,
    #[metastructure(field = "device.locale")]
    pub device_locale: Annotated<String>,
    #[metastructure(field = "device.model_id")]
    pub device_model_id: Annotated<String>,
    #[metastructure(field = "device.name")]
    pub device_name: Annotated<String>,
    #[metastructure(field = "device.online")]
    pub device_online: Annotated<String>,
    #[metastructure(field = "device.orientation")]
    pub device_orientation: Annotated<String>,
    #[metastructure(field = "device.screen_density")]
    pub device_screen_density: Annotated<String>,
    #[metastructure(field = "device.screen_dpi")]
    pub device_screen_dpi: Annotated<String>,
    #[metastructure(field = "device.screen_height_pixels")]
    pub device_screen_height_pixels: Annotated<String>,
    #[metastructure(field = "device.screen_width_pixels")]
    pub device_screen_width_pixels: Annotated<String>,
    #[metastructure(field = "device.simulator")]
    pub device_simulator: Annotated<String>,
    #[metastructure(field = "device.uuid")]
    pub device_uuid: Annotated<String>,
    #[metastructure(field = "app.device")]
    pub app_device: Annotated<String>,
    #[metastructure(field = "device.model")]
    pub device_model: Annotated<String>,
    pub runtime: Annotated<String>,
    #[metastructure(field = "runtime.name")]
    pub runtime_name: Annotated<String>,
    pub browser: Annotated<String>,
    pub os: Annotated<String>,
    #[metastructure(field = "os.rooted")]
    pub os_rooted: Annotated<String>,
    #[metastructure(field = "gpu.name")]
    pub gpu_name: Annotated<String>,
    #[metastructure(field = "gpu.vendor")]
    pub gpu_vendor: Annotated<String>,
    #[metastructure(field = "monitor.id")]
    pub monitor_id: Annotated<String>,
    #[metastructure(field = "monitor.slug")]
    pub monitor_slug: Annotated<String>,
    #[metastructure(field = "request.url")]
    pub request_url: Annotated<String>,
    #[metastructure(field = "request.method")]
    pub request_method: Annotated<String>,
    // Mobile OS the transaction originated from(String).
    #[metastructure(field = "os.name")]
    pub os_name: Annotated<String>,
    pub action: Annotated<String>,
    pub category: Annotated<String>,
    pub description: Annotated<String>,
    pub domain: Annotated<String>,
    pub raw_domain: Annotated<String>,
    pub group: Annotated<String>,
    #[metastructure(field = "http.decoded_response_content_length")]
    pub http_decoded_response_content_length: Annotated<String>,
    #[metastructure(field = "http.response_content_length")]
    pub http_response_content_length: Annotated<String>,
    #[metastructure(field = "http.response_transfer_size")]
    pub http_response_transfer_size: Annotated<String>,
    #[metastructure(field = "resource.render_blocking_status")]
    pub resource_render_blocking_status: Annotated<String>,
    pub op: Annotated<String>,
    pub status: Annotated<String>,
    pub status_code: Annotated<String>,
    pub system: Annotated<String>,
    /// Contributes to Time-To-Initial-Display(String).
    pub ttid: Annotated<String>,
    /// Contributes to Time-To-Full-Display(String).
    pub ttfd: Annotated<String>,
    /// File extension for resource spans(String).
    pub file_extension: Annotated<String>,
    /// Span started on main thread(String).
    pub main_thread: Annotated<String>,
    /// The start type of the application when the span occurred(String).
    pub app_start_type: Annotated<String>,
    pub replay_id: Annotated<String>,
    #[metastructure(field = "cache.hit")]
    pub cache_hit: Annotated<String>,
    #[metastructure(field = "cache.key")]
    pub cache_key: Annotated<String>,
    #[metastructure(field = "trace.status")]
    pub trace_status: Annotated<String>,
    #[metastructure(field = "messaging.destination.name")]
    pub messaging_destination_name: Annotated<String>,
    #[metastructure(field = "messaging.message.id")]
    pub messaging_message_id: Annotated<String>,
    #[metastructure(field = "messaging.operation.name")]
    pub messaging_operation_name: Annotated<String>,
    #[metastructure(field = "messaging.operation.type")]
    pub messaging_operation_type: Annotated<String>,
    #[metastructure(field = "thread.name")]
    pub thread_name: Annotated<String>,
    #[metastructure(field = "thread.id")]
    pub thread_id: Annotated<String>,
    pub profiler_id: Annotated<String>,
    #[metastructure(field = "user.geo.city")]
    pub user_city: Annotated<String>,
    #[metastructure(field = "user.geo.country_code")]
    pub user_country_code: Annotated<String>,
    #[metastructure(field = "user.geo.region")]
    pub user_region: Annotated<String>,
    #[metastructure(field = "user.geo.subdivision")]
    pub user_subdivision: Annotated<String>,
    #[metastructure(field = "user.geo.subregion")]
    pub user_subregion: Annotated<String>,
    pub name: Annotated<String>,
    // no need for an `other` entry here because these fields are added server-side.
    // If an upstream relay does not recognize a field it will be dropped.
}

impl Getter for SentryTags {
    fn get_value(&self, path: &str) -> Option<Val<'_>> {
        let value = match path {
            "action" => &self.action,
            "app_start_type" => &self.app_start_type,
            "browser.name" => &self.browser_name,
            "cache.hit" => &self.cache_hit,
            "cache.key" => &self.cache_key,
            "category" => &self.category,
            "description" => &self.description,
            "device.class" => &self.device_class,
            "device.family" => &self.device_family,
            "device.arch" => &self.device_arch,
            "device.battery_level" => &self.device_battery_level,
            "device.brand" => &self.device_brand,
            "device.charging" => &self.device_charging,
            "device.locale" => &self.device_locale,
            "device.model_id" => &self.device_model_id,
            "device.name" => &self.device_name,
            "device.online" => &self.device_online,
            "device.orientation" => &self.device_orientation,
            "device.screen_density" => &self.device_screen_density,
            "device.screen_dpi" => &self.device_screen_dpi,
            "device.screen_height_pixels" => &self.device_screen_height_pixels,
            "device.screen_width_pixels" => &self.device_screen_width_pixels,
            "device.simulator" => &self.device_simulator,
            "device.uuid" => &self.device_uuid,
            "app.device" => &self.app_device,
            "device.model" => &self.device_model,
            "runtime" => &self.runtime,
            "runtime.name" => &self.runtime_name,
            "browser" => &self.browser,
            "os" => &self.os,
            "os.rooted" => &self.os_rooted,
            "gpu.name" => &self.gpu_name,
            "gpu.vendor" => &self.gpu_vendor,
            "monitor.id" => &self.monitor_id,
            "monitor.slug" => &self.monitor_slug,
            "request.url" => &self.request_url,
            "request.method" => &self.request_method,
            "domain" => &self.domain,
            "environment" => &self.environment,
            "file_extension" => &self.file_extension,
            "group" => &self.group,
            "http.decoded_response_content_length" => &self.http_decoded_response_content_length,
            "http.response_content_length" => &self.http_response_content_length,
            "http.response_transfer_size" => &self.http_response_transfer_size,
            "main_thread" => &self.main_thread,
            "messaging.destination.name" => &self.messaging_destination_name,
            "messaging.message.id" => &self.messaging_message_id,
            "messaging.operation.name" => &self.messaging_operation_name,
            "messaging.operation.type" => &self.messaging_operation_type,
            "mobile" => &self.mobile,
            "name" => &self.name,
            "op" => &self.op,
            "os.name" => &self.os_name,
            "platform" => &self.platform,
            "profiler_id" => &self.profiler_id,
            "raw_domain" => &self.raw_domain,
            "release" => &self.release,
            "replay_id" => &self.replay_id,
            "resource.render_blocking_status" => &self.resource_render_blocking_status,
            "sdk.name" => &self.sdk_name,
            "sdk.version" => &self.sdk_version,
            "status_code" => &self.status_code,
            "status" => &self.status,
            "system" => &self.system,
            "thread.id" => &self.thread_id,
            "thread.name" => &self.thread_name,
            "trace.status" => &self.trace_status,
            "transaction.method" => &self.transaction_method,
            "transaction.op" => &self.transaction_op,
            "ttfd" => &self.ttfd,
            "ttid" => &self.ttid,
            "user.email" => &self.user_email,
            "user.geo.city" => &self.user_city,
            "user.geo.country_code" => &self.user_country_code,
            "user.geo.region" => &self.user_region,
            "user.geo.subdivision" => &self.user_subdivision,
            "user.geo.subregion" => &self.user_subregion,
            "user.id" => &self.user_id,
            "user.ip" => &self.user_ip,
            "user.username" => &self.user_username,
            "user" => &self.user,
            _ => return None,
        };
        Some(value.as_str()?.into())
    }
}

/// Determines the `Pii` value for a field of [`SpanData`] by looking it up in `relay-conventions`.
///
/// If the field is not found in the conventions, this returns `Pii::True`
/// as a precaution.
fn span_data_pii_from_conventions(state: &ProcessingState) -> Pii {
    fn inner(state: &ProcessingState) -> Option<Pii> {
        // `state.keys().next()` is the _last_ segment in the state's
        // path, i.e. the field name.
        let key = state.keys().next()?;

        match relay_conventions::attribute_info(key)?.apply_scrubbing {
            relay_conventions::ApplyScrubbing::Auto => Some(Pii::True),
            relay_conventions::ApplyScrubbing::Never => Some(Pii::False),
            relay_conventions::ApplyScrubbing::Manual => Some(Pii::Maybe),
        }
    }

    inner(state).unwrap_or(Pii::True)
}

/// Arbitrary additional data on a span.
///
/// Besides arbitrary user data, this type also contains SDK-provided fields used by the
/// product (see <https://develop.sentry.dev/sdk/performance/span-data-conventions/>).
#[derive(Clone, Debug, Default, PartialEq, Empty, FromValue, IntoValue, ProcessValue)]
#[metastructure(trim = false, pii = "span_data_pii_from_conventions")]
pub struct SpanData {
    /// Other fields in `span.data`.
    #[metastructure(
        additional_properties,
        retain = true,
        skip_serialization = "null" // applies to child elements
    )]
    pub other: Object<Value>,
}

impl SpanData {
    /// Returns an annotated attribute from span data.
    pub fn get(&self, key: &str) -> Option<&Annotated<Value>> {
        self.other.get(key)
    }

    /// Returns an attribute value from span data.
    pub fn get_value(&self, key: &str) -> Option<&Value> {
        self.get(key).and_then(Annotated::value)
    }

    /// Returns a string attribute from span data.
    pub fn get_str(&self, key: &str) -> Option<&str> {
        self.get_value(key)?.as_str()
    }

    /// Returns whether span data contains an attribute.
    pub fn contains(&self, key: &str) -> bool {
        self.other.contains_key(key)
    }

    /// Inserts an annotated attribute into span data.
    pub fn insert(&mut self, key: impl Into<String>, value: Annotated<Value>) {
        self.other.insert(key.into(), value);
    }

    /// Inserts an attribute into span data.
    pub fn insert_value<T>(&mut self, key: impl Into<String>, value: T)
    where
        T: IntoValue,
    {
        self.insert(key, Annotated::new(value.into_value()));
    }

    /// Removes an attribute from span data.
    pub fn remove(&mut self, key: &str) -> Option<Annotated<Value>> {
        self.other.remove(key)
    }
}

impl Getter for SpanData {
    fn get_value(&self, path: &str) -> Option<Val<'_>> {
        let escaped = path.replace("\\.", "\0");
        let mut path = escaped.split('.').map(|s| s.replace('\0', "."));
        let root = path.next()?;

        let mut val = self.get(&root)?.value()?;
        for part in path {
            // While there is path segments left, `val` has to be an Object.
            let relay_protocol::Value::Object(map) = val else {
                return None;
            };
            val = map.get(&part)?.value()?;
        }
        Some(val.into())
    }
}

impl From<Object<Value>> for SpanData {
    fn from(other: Object<Value>) -> Self {
        Self { other }
    }
}

impl<const N: usize> From<[(String, Annotated<Value>); N]> for SpanData {
    fn from(value: [(String, Annotated<Value>); N]) -> Self {
        Self::from(Object::from(value))
    }
}

/// A link from a span to another span.
#[derive(Clone, Debug, Default, PartialEq, Empty, FromValue, IntoValue, ProcessValue)]
#[metastructure(trim = false)]
pub struct SpanLink {
    /// The trace id of the linked span
    #[metastructure(required = true, trim = false)]
    pub trace_id: Annotated<TraceId>,

    /// The span id of the linked span
    #[metastructure(required = true, trim = false)]
    pub span_id: Annotated<SpanId>,

    /// Whether the linked span was positively/negatively sampled
    #[metastructure(trim = false)]
    pub sampled: Annotated<bool>,

    /// Span link attributes, similar to span attributes/data
    #[metastructure(pii = "maybe", trim = false)]
    pub attributes: Annotated<Object<Value>>,

    /// Additional arbitrary fields for forwards compatibility.
    #[metastructure(additional_properties, retain = true, pii = "maybe", trim = false)]
    pub other: Object<Value>,
}

/// The route in the application, set by React Native SDK.
#[derive(Clone, Debug, Default, PartialEq, Empty, IntoValue, ProcessValue)]
pub struct Route {
    /// The name of the route.
    #[metastructure(pii = "maybe", skip_serialization = "empty")]
    pub name: Annotated<String>,

    /// Parameters assigned to this route.
    #[metastructure(
        pii = "true",
        skip_serialization = "empty",
        max_depth = 5,
        max_bytes = 2048
    )]
    pub params: Annotated<Object<Value>>,

    /// Additional arbitrary fields for forwards compatibility.
    #[metastructure(
        additional_properties,
        retain = true,
        pii = "maybe",
        skip_serialization = "empty"
    )]
    pub other: Object<Value>,
}

impl FromValue for Route {
    fn from_value(value: Annotated<Value>) -> Annotated<Self>
    where
        Self: Sized,
    {
        match value {
            Annotated(Some(Value::String(name)), meta) => Annotated(
                Some(Route {
                    name: Annotated::new(name),
                    ..Default::default()
                }),
                meta,
            ),
            Annotated(Some(Value::Object(mut values)), meta) => {
                let mut route: Route = Default::default();
                if let Some(Annotated(Some(Value::String(name)), _)) = values.remove("name") {
                    route.name = Annotated::new(name);
                }
                if let Some(Annotated(Some(Value::Object(params)), _)) = values.remove("params") {
                    route.params = Annotated::new(params);
                }

                if !values.is_empty() {
                    route.other = values;
                }

                Annotated(Some(route), meta)
            }
            Annotated(None, meta) => Annotated(None, meta),
            Annotated(Some(value), mut meta) => {
                meta.add_error(Error::expected("route expected to be an object"));
                meta.set_original_value(Some(value));
                Annotated(None, meta)
            }
        }
    }
}

/// The kind of a span.
///
/// This corresponds to OTEL's kind enum, plus a
/// catchall variant for forward compatibility.
#[derive(Clone, Debug, PartialEq, ProcessValue, Default)]
pub enum SpanKind {
    /// An operation internal to an application.
    #[default]
    Internal,
    /// Server-side processing requested by a client.
    Server,
    /// A request from a client to a server.
    Client,
    /// Scheduling of an operation.
    Producer,
    /// Processing of a scheduled operation.
    Consumer,
    /// Unknown kind, for forward compatibility.
    Unknown(String),
}

impl SpanKind {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Internal => "internal",
            Self::Server => "server",
            Self::Client => "client",
            Self::Producer => "producer",
            Self::Consumer => "consumer",
            Self::Unknown(s) => s.as_str(),
        }
    }
}

impl Empty for SpanKind {
    fn is_empty(&self) -> bool {
        false
    }
}

#[derive(Debug)]
pub struct ParseSpanKindError;

impl std::str::FromStr for SpanKind {
    type Err = ParseSpanKindError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(match s {
            "internal" => SpanKind::Internal,
            "server" => SpanKind::Server,
            "client" => SpanKind::Client,
            "producer" => SpanKind::Producer,
            "consumer" => SpanKind::Consumer,
            other => SpanKind::Unknown(other.to_owned()),
        })
    }
}

impl fmt::Display for SpanKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl FromValue for SpanKind {
    fn from_value(value: Annotated<Value>) -> Annotated<Self>
    where
        Self: Sized,
    {
        match value {
            Annotated(Some(Value::String(s)), meta) => Annotated(SpanKind::from_str(&s).ok(), meta),
            Annotated(_, meta) => Annotated(None, meta),
        }
    }
}

impl IntoValue for SpanKind {
    fn into_value(self) -> Value
    where
        Self: Sized,
    {
        Value::String(self.to_string())
    }

    fn serialize_payload<S>(
        &self,
        s: S,
        _behavior: relay_protocol::SkipSerialization,
    ) -> Result<S::Ok, S::Error>
    where
        Self: Sized,
        S: serde::Serializer,
    {
        s.serialize_str(self.as_str())
    }
}

#[cfg(test)]
mod tests {
    use crate::protocol::Measurement;
    use chrono::{TimeZone, Utc};
    use relay_base_schema::metrics::{InformationUnit, MetricUnit};
    use relay_conventions::attributes::*;
    use relay_protocol::RuleCondition;
    use similar_asserts::assert_eq;

    use super::*;

    /// Test that span data attributes expected to follow sentry conventions actually do so. This
    /// is achieved by 1) creating a json which uses sentry conventions constants, 2) creating a
    /// `SpanData` object from the json, and 3) verifying that the json values end up in the
    /// expected `SpanData` fields (which wouldn't happen if the sentry conventions constants don't
    /// match the declared field names).
    #[test]
    fn test_span_data_attributes_follow_sentry_conventions() {
        let my_trace = &"my_trace".to_owned();
        let my_transaction = &"my_transaction".to_owned();
        let my_project_id = &"my_project_id".to_owned();
        let json = format!(
            r#"{{
                "{SENTRY__DSC__TRACE_ID}": "{my_trace}",
                "{SENTRY__DSC__TRANSACTION}": "{my_transaction}",
                "{SENTRY__DSC__PROJECT_ID}": "{my_project_id}"
            }}"#,
        );
        let data = Annotated::<SpanData>::from_json(&json).unwrap();
        let data = data.value().unwrap();
        assert_eq!(data.get_str(SENTRY__DSC__TRACE_ID), Some(my_trace.as_str()));
        assert_eq!(
            data.get_str(SENTRY__DSC__TRANSACTION),
            Some(my_transaction.as_str())
        );
        assert_eq!(
            data.get_str(SENTRY__DSC__PROJECT_ID),
            Some(my_project_id.as_str())
        );
    }

    #[test]
    fn test_span_serialization() {
        let json = r#"{
  "timestamp": 0.0,
  "start_timestamp": -63158400.0,
  "exclusive_time": 1.23,
  "op": "operation",
  "span_id": "fa90fdead5f74052",
  "trace_id": "4c79f60c11214eb38604f4ae0781bfb2",
  "status": "ok",
  "description": "desc",
  "origin": "auto.http",
  "links": [
    {
      "trace_id": "4c79f60c11214eb38604f4ae0781bfb2",
      "span_id": "fa90fdead5f74052",
      "sampled": true,
      "attributes": {
        "boolAttr": true,
        "numAttr": 123,
        "stringAttr": "foo"
      }
    }
  ],
  "measurements": {
    "memory": {
      "value": 9001.0,
      "unit": "byte"
    }
  },
  "kind": "server"
}"#;
        let mut measurements = Object::new();
        measurements.insert(
            "memory".into(),
            Annotated::new(Measurement {
                value: Annotated::new(9001.0.try_into().unwrap()),
                unit: Annotated::new(MetricUnit::Information(InformationUnit::Byte)),
            }),
        );

        let links = Annotated::new(vec![Annotated::new(SpanLink {
            trace_id: Annotated::new("4c79f60c11214eb38604f4ae0781bfb2".parse().unwrap()),
            span_id: Annotated::new("fa90fdead5f74052".parse().unwrap()),
            sampled: Annotated::new(true),
            attributes: Annotated::new({
                let mut map: std::collections::BTreeMap<String, Annotated<Value>> = Object::new();
                map.insert(
                    "stringAttr".into(),
                    Annotated::new(Value::String("foo".into())),
                );
                map.insert("numAttr".into(), Annotated::new(Value::I64(123)));
                map.insert("boolAttr".into(), Value::Bool(true).into());
                map
            }),
            ..Default::default()
        })]);

        let span = Annotated::new(Span {
            timestamp: Annotated::new(Utc.with_ymd_and_hms(1970, 1, 1, 0, 0, 0).unwrap().into()),
            start_timestamp: Annotated::new(
                Utc.with_ymd_and_hms(1968, 1, 1, 0, 0, 0).unwrap().into(),
            ),
            exclusive_time: Annotated::new(1.23),
            description: Annotated::new("desc".to_owned()),
            op: Annotated::new("operation".to_owned()),
            trace_id: Annotated::new("4c79f60c11214eb38604f4ae0781bfb2".parse().unwrap()),
            span_id: Annotated::new("fa90fdead5f74052".parse().unwrap()),
            status: Annotated::new(SpanStatus::Ok),
            origin: Annotated::new("auto.http".to_owned()),
            kind: Annotated::new(SpanKind::Server),
            measurements: Annotated::new(Measurements(measurements)),
            links,
            ..Default::default()
        });
        assert_eq!(json, span.to_json_pretty().unwrap());

        let span_from_string = Annotated::from_json(json).unwrap();
        assert_eq!(span, span_from_string);
    }

    #[test]
    fn test_getter_span_data() {
        let span = Annotated::<Span>::from_json(
            r#"{
                "data": {
                    "foo": {"bar": 1},
                    "foo.bar": 2
                },
                "measurements": {
                    "some": {"value": 100.0}
                }
            }"#,
        )
        .unwrap()
        .into_value()
        .unwrap();

        assert_eq!(span.get_value("span.data.foo.bar"), Some(Val::I64(1)));
        assert_eq!(span.get_value(r"span.data.foo\.bar"), Some(Val::I64(2)));

        assert_eq!(span.get_value("span.data"), None);
        assert_eq!(span.get_value("span.data."), None);
        assert_eq!(span.get_value("span.data.x"), None);

        assert_eq!(
            span.get_value("span.measurements.some.value"),
            Some(Val::F64(100.0))
        );
    }

    #[test]
    fn test_getter_was_transaction() {
        let mut span = Span::default();
        assert_eq!(
            span.get_value("span.was_transaction"),
            Some(Val::Bool(false))
        );
        assert!(RuleCondition::eq("span.was_transaction", false).matches(&span));
        assert!(!RuleCondition::eq("span.was_transaction", true).matches(&span));

        span.was_transaction.set_value(Some(false));
        assert_eq!(
            span.get_value("span.was_transaction"),
            Some(Val::Bool(false))
        );
        assert!(RuleCondition::eq("span.was_transaction", false).matches(&span));
        assert!(!RuleCondition::eq("span.was_transaction", true).matches(&span));

        span.was_transaction.set_value(Some(true));
        assert_eq!(
            span.get_value("span.was_transaction"),
            Some(Val::Bool(true))
        );
        assert!(RuleCondition::eq("span.was_transaction", true).matches(&span));
        assert!(!RuleCondition::eq("span.was_transaction", false).matches(&span));
    }

    #[test]
    fn test_span_fields_as_event() {
        let span = Annotated::<Span>::from_json(
            r#"{
                "data": {
                    "sentry.release": "1.0",
                    "sentry.environment": "prod",
                    "sentry.segment.name": "/api/endpoint"
                }
            }"#,
        )
        .unwrap()
        .into_value()
        .unwrap();

        assert_eq!(span.get_value("event.release"), Some(Val::String("1.0")));
        assert_eq!(
            span.get_value("event.environment"),
            Some(Val::String("prod"))
        );
        assert_eq!(
            span.get_value("event.transaction"),
            Some(Val::String("/api/endpoint"))
        );
    }

    #[test]
    fn test_span_duration() {
        let span = Annotated::<Span>::from_json(
            r#"{
                "start_timestamp": 1694732407.8367,
                "timestamp": 1694732408.31451233
            }"#,
        )
        .unwrap()
        .into_value()
        .unwrap();

        assert_eq!(span.get_value("span.duration"), Some(Val::F64(477.812)));
    }

    #[test]
    fn test_span_data() {
        let data = r#"{
        "foo": 2,
        "bar": "3",
        "db.system.name": "mysql",
        "code.filepath": "task.py",
        "code.lineno": 123,
        "code.function": "fn()",
        "code.namespace": "ns",
        "frames.slow": 1,
        "frames.frozen": 2,
        "frames.total": 9,
        "frames.delay": 100,
        "messaging.destination.name": "default",
        "messaging.message.retry.count": 3,
        "messaging.message.receive.latency": 40,
        "messaging.message.body.size": 100,
        "messaging.message.id": "abc123",
        "messaging.operation.name": "publish",
        "messaging.operation.type": "create",
        "user_agent.original": "Chrome",
        "url.full": "my_url.com",
        "client.address": "192.168.0.1"
    }"#;
        let mut data = Annotated::<SpanData>::from_json(data)
            .unwrap()
            .into_value()
            .unwrap();
        insta::assert_debug_snapshot!(data, @r###"
        SpanData {
            other: {
                "bar": String(
                    "3",
                ),
                "client.address": String(
                    "192.168.0.1",
                ),
                "code.filepath": String(
                    "task.py",
                ),
                "code.function": String(
                    "fn()",
                ),
                "code.lineno": I64(
                    123,
                ),
                "code.namespace": String(
                    "ns",
                ),
                "db.system.name": String(
                    "mysql",
                ),
                "foo": I64(
                    2,
                ),
                "frames.delay": I64(
                    100,
                ),
                "frames.frozen": I64(
                    2,
                ),
                "frames.slow": I64(
                    1,
                ),
                "frames.total": I64(
                    9,
                ),
                "messaging.destination.name": String(
                    "default",
                ),
                "messaging.message.body.size": I64(
                    100,
                ),
                "messaging.message.id": String(
                    "abc123",
                ),
                "messaging.message.receive.latency": I64(
                    40,
                ),
                "messaging.message.retry.count": I64(
                    3,
                ),
                "messaging.operation.name": String(
                    "publish",
                ),
                "messaging.operation.type": String(
                    "create",
                ),
                "url.full": String(
                    "my_url.com",
                ),
                "user_agent.original": String(
                    "Chrome",
                ),
            },
        }
        "###);

        assert_eq!(
            data.get("foo").and_then(Annotated::value),
            Some(&Value::I64(2))
        );
        assert_eq!(data.get_value("foo"), Some(&Value::I64(2)));
        assert_eq!(data.get_str("bar"), Some("3"));
        assert_eq!(data.get_str("foo"), None);
        data.insert("bool", Annotated::new(Value::Bool(true)));
        assert_eq!(data.get_value("bool"), Some(&Value::Bool(true)));
        data.insert_value("string", "value".to_owned());
        assert_eq!(data.get_str("string"), Some("value"));
        assert!(data.contains("string"));
        assert_eq!(
            data.remove("string").and_then(Annotated::into_value),
            Some(Value::String("value".to_owned()))
        );
        assert!(!data.contains("string"));
        assert_eq!(
            Getter::get_value(&data, "db\\.system\\.name"),
            Some(Val::String("mysql"))
        );
        assert_eq!(
            Getter::get_value(&data, "code\\.lineno"),
            Some(Val::U64(123))
        );
        assert_eq!(
            Getter::get_value(&data, "code\\.function"),
            Some(Val::String("fn()"))
        );
        assert_eq!(
            Getter::get_value(&data, "code\\.namespace"),
            Some(Val::String("ns"))
        );
        assert_eq!(data.get_value("unknown"), None);
    }

    #[test]
    fn test_span_data_empty_well_known_field() {
        let span = r#"{
            "data": {
                "lcp.url": ""
            }
        }"#;
        let span: Annotated<Span> = Annotated::from_json(span).unwrap();
        assert_eq!(span.to_json().unwrap(), r#"{"data":{"lcp.url":""}}"#);
    }

    #[test]
    fn test_span_data_empty_custom_field() {
        let span = r#"{
            "data": {
                "custom_field_empty": ""
            }
        }"#;
        let span: Annotated<Span> = Annotated::from_json(span).unwrap();
        assert_eq!(
            span.to_json().unwrap(),
            r#"{"data":{"custom_field_empty":""}}"#
        );
    }

    #[test]
    fn test_span_data_completely_empty() {
        let span = r#"{
            "data": {}
        }"#;
        let span: Annotated<Span> = Annotated::from_json(span).unwrap();
        assert_eq!(span.to_json().unwrap(), r#"{"data":{}}"#);
    }

    #[test]
    fn test_span_links() {
        let span = r#"{
            "links": [
                {
                    "trace_id": "5c79f60c11214eb38604f4ae0781bfb2",
                    "span_id": "ab90fdead5f74052",
                    "sampled": true,
                    "attributes": {
                        "sentry.link.type": "previous_trace"
                    }
                },
                {
                    "trace_id": "4c79f60c11214eb38604f4ae0781bfb2",
                    "span_id": "fa90fdead5f74052",
                    "sampled": true,
                    "attributes": {
                        "sentry.link.type": "next_trace"
                    }
                }
            ]
        }"#;

        let span: Annotated<Span> = Annotated::from_json(span).unwrap();
        assert_eq!(
            span.to_json().unwrap(),
            r#"{"links":[{"trace_id":"5c79f60c11214eb38604f4ae0781bfb2","span_id":"ab90fdead5f74052","sampled":true,"attributes":{"sentry.link.type":"previous_trace"}},{"trace_id":"4c79f60c11214eb38604f4ae0781bfb2","span_id":"fa90fdead5f74052","sampled":true,"attributes":{"sentry.link.type":"next_trace"}}]}"#
        );
    }

    #[test]
    fn test_span_kind() {
        let span = Annotated::<Span>::from_json(
            r#"{
                "kind": "???"
            }"#,
        )
        .unwrap()
        .into_value()
        .unwrap();
        assert_eq!(
            span.kind.value().unwrap(),
            &SpanKind::Unknown("???".to_owned())
        );
    }
}
