// @generated by tools/proto-descriptors - DO NOT EDIT.
//
// To regenerate, invoke:
// cargo run -p proto-descriptors -- \
//   --proto-root tests/fixtures/protos \
//   --use-stmts "use super::proto::relay::test::v1::*;" \
//   --out tests/fixtures/descriptors.rs \
//   relay/test/v1/tree.proto

use super::proto::relay::test::v1::*;
use relay_serialization::prost::Error;
use relay_serialization::prost::MessageDesc;
use relay_serialization::prost::decode;
pub trait Decodable {
    fn decode_bounded(buf: &[u8], max_ops: usize) -> Result<Self, Error>
    where
        Self: Sized;
}

/// `relay.test.common.v1.Metadata`
pub static METADATA: MessageDesc = MessageDesc {
    name: "relay.test.common.v1.Metadata",
    nested: &[(2, &TAG)],
};

/// `relay.test.common.v1.Tag`
pub static TAG: MessageDesc = MessageDesc {
    name: "relay.test.common.v1.Tag",
    nested: &[],
};

/// `relay.test.v1.Leaf`
pub static LEAF: MessageDesc = MessageDesc {
    name: "relay.test.v1.Leaf",
    nested: &[(9, &LEAF)],
};

/// `relay.test.v1.Tree`
pub static TREE: MessageDesc = MessageDesc {
    name: "relay.test.v1.Tree",
    nested: &[(1, &TREE_NODE), (2, &TREE_NODE), (3, &METADATA)],
};

/// `relay.test.v1.Tree.Node`
pub static TREE_NODE: MessageDesc = MessageDesc {
    name: "relay.test.v1.Tree.Node",
    nested: &[(2, &LEAF), (3, &TREE_NODE)],
};

impl Decodable for Tree {
    fn decode_bounded(buf: &[u8], max_ops: usize) -> Result<Self, Error> {
        decode(buf, &TREE, max_ops)
    }
}

impl Decodable for Leaf {
    fn decode_bounded(buf: &[u8], max_ops: usize) -> Result<Self, Error> {
        decode(buf, &LEAF, max_ops)
    }
}
