class RelayError:
    code: int | None = None

class Unknown(RelayError): ...
class InvalidJsonError(RelayError): ...
class KeyParseErrorBadEncoding(RelayError): ...
class KeyParseErrorBadKey(RelayError): ...
class UnpackErrorBadSignature(RelayError): ...
class UnpackErrorBadPayload(RelayError): ...
class UnpackErrorSignatureExpired(RelayError): ...
class UnpackErrorBadEncoding(RelayError): ...
class ProcessingErrorInvalidTransaction(RelayError): ...
class ProcessingErrorInvalidGeoIp(RelayError): ...
class InvalidReleaseErrorTooLong(RelayError): ...
class InvalidReleaseErrorRestrictedName(RelayError): ...
class InvalidReleaseErrorBadCharacters(RelayError): ...
