// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tree {
    #[prost(message, optional, tag = "1")]
    pub root: ::core::option::Option<tree::Node>,
    #[prost(message, repeated, tag = "2")]
    pub forest: ::prost::alloc::vec::Vec<tree::Node>,
    /// Lives in an imported file, so it is only resolvable with `--include_imports`.
    #[prost(message, optional, tag = "3")]
    pub metadata: ::core::option::Option<super::common::v1::Metadata>,
}
/// Nested message and enum types in `Tree`.
pub mod tree {
    /// A type nested inside another message, so the generator has to flatten the path.
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Node {
        #[prost(string, tag = "1")]
        pub label: ::prost::alloc::string::String,
        #[prost(message, repeated, tag = "2")]
        pub leaves: ::prost::alloc::vec::Vec<super::Leaf>,
        /// Recursion through a nested type.
        #[prost(message, repeated, tag = "3")]
        pub children: ::prost::alloc::vec::Vec<Node>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Leaf {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub number: u64,
    #[prost(double, tag = "3")]
    pub real: f64,
    #[prost(fixed32, tag = "4")]
    pub fixed: u32,
    #[prost(bytes = "vec", tag = "5")]
    pub blob: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, repeated, tag = "6")]
    pub numbers: ::prost::alloc::vec::Vec<u64>,
    #[prost(enumeration = "Kind", tag = "7")]
    pub kind: i32,
    #[prost(oneof = "leaf::Value", tags = "8, 9")]
    pub value: ::core::option::Option<leaf::Value>,
}
/// Nested message and enum types in `Leaf`.
pub mod leaf {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag = "8")]
        Name(::prost::alloc::string::String),
        /// Recursion through a `oneof`.
        #[prost(message, tag = "9")]
        Leaf(::prost::alloc::boxed::Box<super::Leaf>),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Kind {
    Unspecified = 0,
    One = 1,
}
impl Kind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "KIND_UNSPECIFIED",
            Self::One => "KIND_ONE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "KIND_ONE" => Some(Self::One),
            _ => None,
        }
    }
}
