[package]
name = "relay-serialization"
authors = ["Sentry <oss@sentry.io>"]
description = "Bounded deserialization for Relay"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
version = "26.8.0"
edition = "2024"
license-file = "../LICENSE.md"
publish = false

[lints]
workspace = true

[dependencies]
prost = { workspace = true }
serde = { workspace = true }
leb128 = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
relay-serialization-derive = { workspace = true }
trybuild = { workspace = true }
