// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Trace {
    #[prost(message, repeated, tag = "1")]
    pub packet: ::prost::alloc::vec::Vec<TracePacket>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TracePacket {
    #[prost(uint64, optional, tag = "8")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(message, optional, tag = "12")]
    pub interned_data: ::core::option::Option<InternedData>,
    #[prost(uint32, optional, tag = "13")]
    pub sequence_flags: ::core::option::Option<u32>,
    #[prost(oneof = "trace_packet::OptionalTrustedPacketSequenceId", tags = "10")]
    pub optional_trusted_packet_sequence_id:
        ::core::option::Option<trace_packet::OptionalTrustedPacketSequenceId>,
    /// Only the oneof variants we care about; prost will skip the rest.
    #[prost(oneof = "trace_packet::Data", tags = "2, 6, 54, 60, 66")]
    pub data: ::core::option::Option<trace_packet::Data>,
}
/// Nested message and enum types in `TracePacket`.
pub mod trace_packet {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum OptionalTrustedPacketSequenceId {
        #[prost(uint32, tag = "10")]
        TrustedPacketSequenceId(u32),
    }
    /// Only the oneof variants we care about; prost will skip the rest.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "2")]
        ProcessTree(super::ProcessTree),
        #[prost(message, tag = "6")]
        ClockSnapshot(super::ClockSnapshot),
        #[prost(message, tag = "54")]
        StreamingProfilePacket(super::StreamingProfilePacket),
        #[prost(message, tag = "60")]
        TrackDescriptor(super::TrackDescriptor),
        #[prost(message, tag = "66")]
        PerfSample(super::PerfSample),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcessTree {
    #[prost(message, repeated, tag = "2")]
    pub threads: ::prost::alloc::vec::Vec<process_tree::Thread>,
}
/// Nested message and enum types in `ProcessTree`.
pub mod process_tree {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Thread {
        #[prost(int32, optional, tag = "1")]
        pub tid: ::core::option::Option<i32>,
        #[prost(string, optional, tag = "2")]
        pub name: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(int32, optional, tag = "3")]
        pub tgid: ::core::option::Option<i32>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClockSnapshot {
    #[prost(message, repeated, tag = "1")]
    pub clocks: ::prost::alloc::vec::Vec<clock_snapshot::Clock>,
    #[prost(uint32, optional, tag = "2")]
    pub primary_trace_clock: ::core::option::Option<u32>,
}
/// Nested message and enum types in `ClockSnapshot`.
pub mod clock_snapshot {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Clock {
        #[prost(uint32, optional, tag = "1")]
        pub clock_id: ::core::option::Option<u32>,
        #[prost(uint64, optional, tag = "2")]
        pub timestamp: ::core::option::Option<u64>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InternedData {
    #[prost(message, repeated, tag = "5")]
    pub function_names: ::prost::alloc::vec::Vec<InternedString>,
    #[prost(message, repeated, tag = "6")]
    pub frames: ::prost::alloc::vec::Vec<Frame>,
    #[prost(message, repeated, tag = "7")]
    pub callstacks: ::prost::alloc::vec::Vec<Callstack>,
    #[prost(message, repeated, tag = "16")]
    pub build_ids: ::prost::alloc::vec::Vec<InternedString>,
    #[prost(message, repeated, tag = "17")]
    pub mapping_paths: ::prost::alloc::vec::Vec<InternedString>,
    #[prost(message, repeated, tag = "19")]
    pub mappings: ::prost::alloc::vec::Vec<Mapping>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InternedString {
    #[prost(uint64, optional, tag = "1")]
    pub iid: ::core::option::Option<u64>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub str: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Frame {
    #[prost(uint64, optional, tag = "1")]
    pub iid: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "2")]
    pub function_name_id: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "3")]
    pub mapping_id: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "4")]
    pub rel_pc: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Mapping {
    #[prost(uint64, optional, tag = "1")]
    pub iid: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "2")]
    pub build_id: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "3")]
    pub start_offset: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "4")]
    pub start: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "5")]
    pub end: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "6")]
    pub load_bias: ::core::option::Option<u64>,
    #[prost(uint64, repeated, packed = "false", tag = "7")]
    pub path_string_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, optional, tag = "8")]
    pub exact_offset: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Callstack {
    #[prost(uint64, optional, tag = "1")]
    pub iid: ::core::option::Option<u64>,
    #[prost(uint64, repeated, packed = "false", tag = "2")]
    pub frame_ids: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PerfSample {
    #[prost(uint32, optional, tag = "1")]
    pub cpu: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub pid: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "3")]
    pub tid: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag = "4")]
    pub callstack_iid: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamingProfilePacket {
    #[prost(uint64, repeated, packed = "false", tag = "1")]
    pub callstack_iid: ::prost::alloc::vec::Vec<u64>,
    #[prost(int64, repeated, packed = "false", tag = "2")]
    pub timestamp_delta_us: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TrackDescriptor {
    #[prost(uint64, optional, tag = "1")]
    pub uuid: ::core::option::Option<u64>,
    #[prost(message, optional, tag = "4")]
    pub thread: ::core::option::Option<ThreadDescriptor>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ThreadDescriptor {
    #[prost(int32, optional, tag = "1")]
    pub pid: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub tid: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "5")]
    pub thread_name: ::core::option::Option<::prost::alloc::string::String>,
}
