---
relay:
  upstream: "http://host.docker.internal:8001/"
  host: 0.0.0.0
  port: 7899
logging:
  level: INFO
  enable_backtraces: false
limits:
  shutdown_timeout: 0
processing:
  enabled: true
  kafka_config:
    - { name: "bootstrap.servers", value: "kafka:9093" }
    # Align with Relay's default `max_envelope_size` size (200 MiB -> 209,715,200 bytes).
    - { name: "message.max.bytes", value: 209715200 }
  redis: redis://redis:6379
