(function() {var implementors = {
"document_metrics":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"document_metrics/struct.ParseSchemaFormatError.html\" title=\"struct document_metrics::ParseSchemaFormatError\">ParseSchemaFormatError</a>"]],
"generate_schema":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"generate_schema/struct.ParseSchemaFormatError.html\" title=\"struct generate_schema::ParseSchemaFormatError\">ParseSchemaFormatError</a>"]],
"relay_auth":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"relay_auth/struct.ParseRelayVersionError.html\" title=\"struct relay_auth::ParseRelayVersionError\">ParseRelayVersionError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"relay_auth/enum.KeyParseError.html\" title=\"enum relay_auth::KeyParseError\">KeyParseError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"relay_auth/enum.UnpackError.html\" title=\"enum relay_auth::UnpackError\">UnpackError</a>"]],
"relay_aws_extension":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"relay_aws_extension/struct.AwsExtensionError.html\" title=\"struct relay_aws_extension::AwsExtensionError\">AwsExtensionError</a>"]],
"relay_common":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"relay_common/struct.ParseEventTypeError.html\" title=\"struct relay_common::ParseEventTypeError\">ParseEventTypeError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"relay_common/struct.ParseSpanStatusError.html\" title=\"struct relay_common::ParseSpanStatusError\">ParseSpanStatusError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"relay_common/struct.ParseProjectKeyError.html\" title=\"struct relay_common::ParseProjectKeyError\">ParseProjectKeyError</a>"]],
"relay_ffi":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"relay_ffi/struct.Panic.html\" title=\"struct relay_ffi::Panic\">Panic</a>"]],
"relay_kafka":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"relay_kafka/enum.ConfigError.html\" title=\"enum relay_kafka::ConfigError\">ConfigError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"relay_kafka/enum.ClientError.html\" title=\"enum relay_kafka::ClientError\">ClientError</a>"]],
"relay_metrics":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"relay_metrics/struct.ParseBucketError.html\" title=\"struct relay_metrics::ParseBucketError\">ParseBucketError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"relay_metrics/struct.AggregateMetricsError.html\" title=\"struct relay_metrics::AggregateMetricsError\">AggregateMetricsError</a>"]],
"relay_quotas":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"relay_quotas/enum.RateLimitingError.html\" title=\"enum relay_quotas::RateLimitingError\">RateLimitingError</a>"]],
"relay_redis":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"relay_redis/enum.RedisError.html\" title=\"enum relay_redis::RedisError\">RedisError</a>"]],
"relay_replays":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"relay_replays/recording/enum.RecordingParseError.html\" title=\"enum relay_replays::recording::RecordingParseError\">RecordingParseError</a>"]],
"relay_system":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.65.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"relay_system/struct.SendError.html\" title=\"struct relay_system::SendError\">SendError</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()